# GET root URL
GET rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/
Accept: text/plain

###

# GET health check
GET rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/health
Accept: application/json

###

# GET all tasks
GET rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/tasks
Accept: application/json

###

# GET a specific task by ID
GET rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/tasks/1
Accept: application/json

###

# GET a task that does not exist
GET rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/tasks/10
Accept: application/json

###

# POST create a new task (valid data)
POST rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
  "title": "Complete Assignment 21",
  "description": "REST API with tasks",
  "user_id": 4,
  "completed": false
}

###

# POST create a new task (missing title)
POST rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
  "description": "REST API with tasks",
  "user_id": 1,
  "completed": false
}

###

# POST create a new task (with an invalid user_id)
POST rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
  "title": "Complete Assignment 21",
  "description": "REST API with tasks",
  "completed": false
}

###

# PUT update a task by ID
PUT rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/tasks/1
Content-Type: application/json

{
  "title": "Complete 21",
  "description": "REST",
  "user_id": 1,
  "completed": false
}

###

# GET all tasks associated with a specific user ID
GET rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/users/1/tasks
Accept: application/json

###

# DELETE a task by ID
DELETE rest-frcvexggc8hserca.mexicocentral-01.azurewebsites.net/tasks/2
